version: '2'
services:
  nginx:
    container_name: crossbow
    image: donbeave/nginx-pagespeed:1.8.0-1
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
